# Generated by Django 4.2.6 on 2024-01-30 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('carnet_identidad', models.CharField(max_length=11, verbose_name='Carnet identidad')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('grado_cientifico', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Doctor', 'Doctor'), ('Máster', 'Máster')], max_length=10, verbose_name='Grado científico')),
                ('categoria_docente', models.CharField(choices=[('Docente', 'Docente'), ('Titular', 'Titular'), ('Auxiliar', 'Auxiliar'), ('Instructor', 'Instructor')], max_length=10, verbose_name='Categoría docente')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('carnet_identidad', models.CharField(max_length=11, verbose_name='Carnet identidad')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=10, verbose_name='Dirección')),
                ('agno_academico', models.CharField(choices=[('2', '2'), ('3', '3'), ('1', '1'), ('4', '4')], max_length=10, verbose_name='Año académico')),
                ('clase', models.ManyToManyField(blank=True, to='university_app.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('agno', models.IntegerField(verbose_name='Año')),
                ('diciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university_app.disciplina')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university_app.profesor')),
            ],
        ),
    ]
