# Generated by Django 4.2.6 on 2024-01-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clase',
            options={'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='agno_academico',
            field=models.CharField(choices=[('4', '4'), ('2', '2'), ('1', '1'), ('3', '3')], max_length=10, verbose_name='Año académico'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='clase',
            field=models.ManyToManyField(blank=True, to='university_app.clase'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='categoria_docente',
            field=models.CharField(choices=[('Auxiliar', 'Auxiliar'), ('Instructor', 'Instructor'), ('Docente', 'Docente'), ('Titular', 'Titular')], max_length=10, verbose_name='Categoría docente'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='grado_cientifico',
            field=models.CharField(choices=[('Máster', 'Máster'), ('Doctor', 'Doctor'), ('Ninguno', 'Ninguno')], max_length=10, verbose_name='Grado científico'),
        ),
    ]
