# Generated by Django 4.2.6 on 2024-01-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0002_alter_clase_options_alter_estudiante_agno_academico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='agno_academico',
            field=models.CharField(choices=[('3', '3'), ('1', '1'), ('4', '4'), ('2', '2')], max_length=10, verbose_name='Año académico'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='categoria_docente',
            field=models.CharField(choices=[('Instructor', 'Instructor'), ('Auxiliar', 'Auxiliar'), ('Docente', 'Docente'), ('Titular', 'Titular')], max_length=10, verbose_name='Categoría docente'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='grado_cientifico',
            field=models.CharField(choices=[('Ninguno', 'Ninguno'), ('Doctor', 'Doctor'), ('Máster', 'Máster')], max_length=10, verbose_name='Grado científico'),
        ),
    ]
